services:

  frontend:
    build : 
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - default

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      # - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    networks:
      - default
      - backend_network

  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Salasana1
    networks:
      - backend_network


networks:
  default:
  backend_network:
